name: firebase_login
description: A new flutter plugin project.
version: 0.0.1
author: Ross Nguyen
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.18.0 # help us to use SVG in our app
  provider: ^4.3.3
  font_awesome_flutter: ^8.11.0
  lottie: ^0.7.0+1

  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.15
  cloud_firestore: ^0.16.0
  firebase_remote_config: ^0.6.0
  flutter_local_notifications: ^4.0.1+1

  crypto: ^2.1.5

  flutter_facebook_auth: ^2.0.2
  google_sign_in: ^4.5.6
  sign_in_with_apple: ^2.5.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: mcysd.flutter.plugin.firebase_login
        pluginClass: FirebaseLoginPlugin
      ios:
        pluginClass: FirebaseLoginPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/firebase_login/assets/icons/Mail.svg
    - packages/firebase_login/assets/icons/Lock.svg
    - packages/firebase_login/assets/icons/kakao-icon.svg
    - packages/firebase_login/assets/icons/google-icon.svg
    - packages/firebase_login/assets/icons/facebook-2.svg
    - packages/firebase_login/assets/icons/Apple.svg
    - packages/firebase_login/assets/animation/congrats.json
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
